#
# MomentoVelocityUtils by fergydanny (https://github.com/dnyferguson)
#
test: true

# MySQL credentials. Used for various parts of this plugin
mysql:
  ip: 'localhost'
  port: '3306'
  user: 'user'
  pass: 'pass'
  db: 'MomentoVelocityUtils'
  maxConnections: 2

# Set what words to look for in the kick reason to kick players fully
# off of the proxy. Normal velocity behavior is to just kick them to hub.
kicking:
  reasons:
    - 'kick'
    - 'kicked'
    - 'ban'
    - 'banned'

# Enable or disable auto server rejoining. Basically when a player gets kicked
# from any server except the excluded ones, this plugin will attempt to reconnect
# them to the server they were just one (useful for reboots).
rejoin:
  enabled: true
  serversExcluded:
    - 'hub'
    - 'hub1'
    - 'hub2'
  # How often in seconds you want to try and move them back
  interval: 30
  # After how many attempts should we stop? Use -1 to never stop
  attempts: 10

# Enable or disable slash server. For example if you have a server called skyblock, this enables players to do /skyblock which will behave the same way as /server skyblock
slashserver:
  enabled: true
